Add logs to 'release' workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -31,7 +31,15 @@ jobs:
             - run: yarn install --frozen-lockfile
 
             - name: Compile contracts
-              run: yarn compile
+              run: |
+                yarn compile
+                if [ ! -d "artifacts" ]; then
+                  echo "Artifacts directory is missing!"
+                  exit 1
+                fi
+
+            - name: Debug artifacts before upload
+              run: ls -R artifacts || echo "No artifacts found"
 
             - name: Save build artifacts
               uses: actions/upload-artifact@v4
