Removing minting functionality from FORT (`Forta.sol`) token contract (#271)
* Remove 'mint()' and 'MINTER_ROLE'

* Comment out token's 'mint' test cases

* Create function to manually overwrite token balances

* Update test suite to overwrite token balances instead of minting

* Create/update necessary infra for mainnet FORT upgrade

* Add relayers for ETH mainnet and Sepolia

* Use v4 of 'upload-artifact' and 'download-artifact'

* Add test case for token version getter

* Add logs to 'release' workflow

* [HOTFIX] Subgraph CI environment (#273)

* Add 'hardhat clean' before 'hardhat compile'

* Remove logs if 'artifacts' not found

* Exit 'compile contracts' if no 'artifacts'

---------

Co-authored-by: Ivan Diaz <ivandiazwm@gmail.com>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -30,11 +30,19 @@ jobs:
                   cache: 'yarn'
             - run: yarn install --frozen-lockfile
 
+            - name: Clean Hardhat Cache
+              run: yarn hardhat clean
+
             - name: Compile contracts
-              run: yarn compile
+              run: |
+                yarn compile
+                if [ ! -d "artifacts" ]; then
+                  echo "Artifacts directory is missing!"
+                  exit 1
+                fi
 
             - name: Save build artifacts
-              uses: actions/upload-artifact@v3
+              uses: actions/upload-artifact@v4
               with:
                   name: contract-artifacts
                   path: |
@@ -57,7 +65,7 @@ jobs:
             - run: yarn install --frozen-lockfile
 
             - name: Get build artifacts
-              uses: actions/download-artifact@v3
+              uses: actions/download-artifact@v4
               with:
                   name: contract-artifacts
 
@@ -185,7 +193,7 @@ jobs:
     #         - run: yarn install --frozen-lockfile
 
     #         - name: Get build artifacts
-    #           uses: actions/download-artifact@v3
+    #           uses: actions/download-artifact@v4
     #           with:
     #               name: contract-artifacts
 
@@ -234,7 +242,7 @@ jobs:
     #         - run: yarn install --frozen-lockfile
 
     #         - name: Get build artifacts
-    #           uses: actions/download-artifact@v3
+    #           uses: actions/download-artifact@v4
     #           with:
     #               name: contract-artifacts
 
@@ -273,7 +281,7 @@ jobs:
     #         - run: yarn install --frozen-lockfile
 
     #         - name: Get build artifacts
-    #           uses: actions/download-artifact@v3
+    #           uses: actions/download-artifact@v4
     #           with:
     #               name: contract-artifacts
 
